-- migrate:up
-- noqa: disable=LT05

-- Bootstrap seed of meta.column_registry: every key known from the OTel signals catalog
-- (docs/research/claude-code-otel-signals.md) and the POC data dictionary, classified
-- promoted / kept / denied. Future promotions and deny decisions ship as their own
-- migrations alongside the DDL change (#16).
--
-- Grain convention: an attr whose meaning is uniform wherever it appears is recorded once
-- with signal_name = '*'; an attr whose meaning differs by signal name (e.g. `type`,
-- `duration_ms`) gets one row per signal name. Resource-block attrs use signal='resource'.
-- Redaction (#8) denylist keys are recorded as denied at '*' (stripped wherever seen);
-- the content attrs (prompt/response/body/body_ref) are recorded under their bearing event.

-- ===== metrics: promoted =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('metrics', '*', 'timeUnixNano', 'promoted', 'ts', 'TIMESTAMPTZ', 'Metric data-point timestamp.', 'time grain', '2026-07-13', NULL),
('metrics', '*', 'metric.name', 'promoted', 'metric_name', 'TEXT', 'OTel instrument name.', 'signal routing', '2026-07-13', NULL),
('metrics', '*', 'metric.type', 'promoted', 'metric_type', 'TEXT', 'Instrument kind: gauge/sum/histogram.', 'temporality handling', '2026-07-13', NULL),
('metrics', '*', 'dataPoint.value', 'promoted', 'value', 'DOUBLE PRECISION', 'Numeric data-point value (delta counters).', 'all measures', '2026-07-13', NULL),
('metrics', '*', 'dataPoint.count', 'promoted', 'count', 'BIGINT', 'Pre-aggregated count on histogram instruments.', NULL, '2026-07-13', NULL),
('metrics', '*', 'dataPoint.value_kind', 'promoted', 'value_kind', 'TEXT', 'Derived: gauge_last/sum_delta/sum_cumulative/hist_sum.', 'delta-only staging filter', '2026-07-13', NULL),
('metrics', '*', 'scope.name', 'promoted', 'scope_name', 'TEXT', 'OTel instrumentation scope.', 'wrapper-vs-native split', '2026-07-13', NULL),
('metrics', '*', 'scope.version', 'promoted', 'scope_version', 'TEXT', 'Instrumentation scope version.', NULL, '2026-07-13', NULL),
('metrics', '*', 'session.id', 'promoted', 'session_id', 'UUID', 'Claude Code session UUID.', 'session facts', '2026-07-13', NULL),
('metrics', '*', 'user.email', 'promoted', 'user_email', 'TEXT', 'Developer identity (normalized lowercase/trim).', 'dim_user join', '2026-07-13', 'identity kept per #6'),
('metrics', '*', 'user.account_uuid', 'promoted', 'user_account_id', 'TEXT', 'Anthropic account UUID.', NULL, '2026-07-13', NULL),
('metrics', '*', 'user.account_id', 'promoted', 'user_account_id', 'TEXT', 'Anthropic tagged account id.', NULL, '2026-07-13', 'coalesced into user_account_id under user.account_uuid'),
('metrics', '*', 'organization.id', 'promoted', 'organization_id', 'TEXT', 'Organization UUID.', NULL, '2026-07-13', NULL),
('metrics', '*', 'model', 'promoted', 'model', 'TEXT', 'Model id (usage/cost/LOC metrics).', 'dim_model', '2026-07-13', NULL),
('metrics', '*', 'app.version', 'promoted', 'cc_version', 'TEXT', 'Claude Code version.', 'install health', '2026-07-13', 'coalesced over resource service.version'),
('metrics', '*', 'query_source', 'promoted', 'query_source', 'TEXT', 'Request origin: main/subagent/auxiliary.', NULL, '2026-07-13', 'on token.usage/cost.usage'),
('metrics', '*', 'effort', 'promoted', 'effort', 'TEXT', 'Reasoning-effort level.', NULL, '2026-07-13', NULL),
('metrics', '*', 'speed', 'promoted', 'speed', 'TEXT', 'fast when fast-mode.', NULL, '2026-07-13', NULL),
('metrics', '*', 'agent.name', 'promoted', 'agent_name', 'TEXT', 'Agent attribution (custom collapses).', NULL, '2026-07-13', NULL),
('metrics', '*', 'skill.name', 'promoted', 'skill_name', 'TEXT', 'Skill attribution.', NULL, '2026-07-13', NULL),
('metrics', '*', 'plugin.name', 'promoted', 'plugin_name', 'TEXT', 'Plugin attribution.', NULL, '2026-07-13', NULL),
('metrics', '*', 'marketplace.name', 'promoted', 'marketplace_name', 'TEXT', 'Marketplace attribution.', NULL, '2026-07-13', NULL),
('metrics', 'claude_code.token.usage', 'type', 'promoted', 'type_label', 'TEXT', 'Token type: input/output/cacheRead/cacheCreation.', 'token breakdown', '2026-07-13', NULL),
('metrics', 'claude_code.active_time.total', 'type', 'promoted', 'type_label', 'TEXT', 'Active-time type: user (keyboard) / cli (tools+AI).', 'active time split', '2026-07-13', NULL),
('metrics', 'claude_code.lines_of_code.count', 'type', 'promoted', 'type_label', 'TEXT', 'LOC change type: added / removed.', 'loc measures', '2026-07-13', NULL),
('metrics', 'claude_code.code_edit_tool.decision', 'tool_name', 'promoted', 'tool_name', 'TEXT', 'Edit/Write/NotebookEdit.', 'fact_edit_decision', '2026-07-13', NULL),
('metrics', 'claude_code.code_edit_tool.decision', 'decision', 'promoted', 'decision', 'TEXT', 'accept / reject.', 'acceptance rate', '2026-07-13', NULL),
('metrics', 'claude_code.code_edit_tool.decision', 'source', 'promoted', 'source', 'TEXT', 'Decision source: config/hook/user_*.', 'auto-vs-human split', '2026-07-13', NULL),
('metrics', 'claude_code.code_edit_tool.decision', 'language', 'promoted', 'language', 'TEXT', 'Detected language.', 'language mix', '2026-07-13', NULL),
('metrics', 'claude_code.session.count', 'start_type', 'promoted', 'start_type', 'TEXT', 'fresh/resume/continue/agents_view.', 'fact_session', '2026-07-13', NULL),
('metrics', 'claude_code.usage.utilization', 'window', 'promoted', 'usage_window', 'TEXT', 'Rate-limit window (5h/7d/...).', 'fact_usage_window', '2026-07-13', 'wrapper telemetry (ADR-0003)'),
('metrics', 'claude_code.usage.reset_in_seconds', 'window', 'promoted', 'usage_window', 'TEXT', 'Rate-limit window (5h/7d/...).', 'fact_usage_window', '2026-07-13', 'wrapper telemetry (ADR-0003)');

-- ===== metrics: kept (blob-only) =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('metrics', '*', 'user.id', 'kept', NULL, NULL, 'Anonymous install id.', NULL, '2026-07-13', NULL),
('metrics', '*', 'terminal.type', 'kept', NULL, NULL, 'Terminal app type.', NULL, '2026-07-13', NULL),
('metrics', '*', 'host.name', 'kept', NULL, NULL, 'Hostname.', NULL, '2026-07-13', NULL),
('metrics', '*', 'app.entrypoint', 'kept', NULL, NULL, 'Launch surface (opt-in).', NULL, '2026-07-13', NULL),
('metrics', '*', 'context_window_size', 'kept', NULL, NULL, 'Context window size.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'fast_mode', 'kept', NULL, NULL, 'Fast-mode flag.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'thinking_enabled', 'kept', NULL, NULL, 'Thinking-enabled flag.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'output_style', 'kept', NULL, NULL, 'Output style.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'repo.owner', 'kept', NULL, NULL, 'Repo owner.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'repo.name', 'kept', NULL, NULL, 'Repo name.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'session_name', 'kept', NULL, NULL, 'Session label.', NULL, '2026-07-13', 'wrapper telemetry'),
('metrics', '*', 'workspace.host_paths', 'kept', NULL, NULL, 'Desktop workspace dirs.', NULL, '2026-07-13', NULL),
('metrics', 'claude_code.token.usage', 'mcp_server.name', 'kept', NULL, NULL, 'MCP server attribution.', NULL, '2026-07-13', 'not promoted on metrics; api_request carries it for bridges'),
('metrics', 'claude_code.token.usage', 'mcp_tool.name', 'kept', NULL, NULL, 'MCP tool attribution.', NULL, '2026-07-13', 'not promoted on metrics'),
('metrics', '*', 'gen_ai.operation.name', 'kept', NULL, NULL, 'GenAI operation.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'gen_ai.provider.name', 'kept', NULL, NULL, 'GenAI provider.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'gen_ai.request.model', 'kept', NULL, NULL, 'GenAI request model.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'gen_ai.response.model', 'kept', NULL, NULL, 'GenAI response model.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'gen_ai.tool.name', 'kept', NULL, NULL, 'GenAI tool.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'gen_ai.token.type', 'kept', NULL, NULL, 'GenAI token type.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'outcome', 'kept', NULL, NULL, 'Connection outcome.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'transport', 'kept', NULL, NULL, 'Transport.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled'),
('metrics', '*', 'error.type', 'kept', NULL, NULL, 'Error type enum.', NULL, '2026-07-13', 'non-Claude-Code (GitHub Copilot); not modeled');

-- ===== resource attrs (all signals) =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('resource', '*', 'service.name', 'kept', NULL, NULL, 'Service name (claude-code).', NULL, '2026-07-13', NULL),
('resource', '*', 'service.version', 'promoted', 'cc_version', 'TEXT', 'Claude Code version.', 'install health', '2026-07-13', 'coalesced under attrs app.version'),
('resource', '*', 'os.type', 'kept', NULL, NULL, 'OS type.', NULL, '2026-07-13', NULL),
('resource', '*', 'os.version', 'kept', NULL, NULL, 'OS version.', NULL, '2026-07-13', NULL),
('resource', '*', 'host.arch', 'kept', NULL, NULL, 'Host architecture.', NULL, '2026-07-13', NULL),
('resource', '*', 'wsl.version', 'kept', NULL, NULL, 'WSL version.', NULL, '2026-07-13', NULL),
('resource', '*', 'claude.deployment_mode', 'kept', NULL, NULL, 'Deployment mode (e.g. 1p test rows).', NULL, '2026-07-13', NULL),
('resource', '*', 'department', 'kept', NULL, NULL, 'Org department (OTEL_RESOURCE_ATTRIBUTES).', NULL, '2026-07-13', 'org dims come from Azure SQL (#9), not the pipeline'),
('resource', '*', 'region', 'kept', NULL, NULL, 'Org region.', NULL, '2026-07-13', 'org dims come from Azure SQL (#9)'),
('resource', '*', 'cost_center', 'kept', NULL, NULL, 'Org cost center.', NULL, '2026-07-13', 'org dims come from Azure SQL (#9)'),
('resource', '*', 'company', 'kept', NULL, NULL, 'Org company.', NULL, '2026-07-13', 'org dims come from Azure SQL (#9)'),
('resource', '*', 'team', 'kept', NULL, NULL, 'Org team.', NULL, '2026-07-13', 'org dims come from Azure SQL (#9)');

-- ===== events: promoted =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('events', '*', 'timeUnixNano', 'promoted', 'event_time', 'TIMESTAMPTZ', 'Log-record timestamp.', 'time grain', '2026-07-13', NULL),
('events', '*', 'event.name', 'promoted', 'event_name', 'TEXT', 'Event name.', 'signal routing', '2026-07-13', NULL),
('events', '*', 'severityText', 'promoted', 'severity', 'TEXT', 'Log severity text.', NULL, '2026-07-13', NULL),
('events', '*', 'logRecord.body', 'promoted', 'body', 'TEXT', 'OTLP log-record body (event-name string for CC events).', NULL, '2026-07-13', 'the log-record body field, not the `body` attribute on api_*_body events (denied)'),
('events', '*', 'severityNumber', 'promoted', 'severity_number', 'SMALLINT', 'Log severity number.', NULL, '2026-07-13', NULL),
('events', '*', 'traceId', 'promoted', 'log_trace_id', 'TEXT', 'Trace id if present.', NULL, '2026-07-13', NULL),
('events', '*', 'spanId', 'promoted', 'log_span_id', 'TEXT', 'Span id if present.', NULL, '2026-07-13', NULL),
('events', '*', 'droppedAttributesCount', 'promoted', 'dropped_attributes_count', 'INTEGER', 'Dropped-attribute count.', 'ingest QA', '2026-07-13', NULL),
('events', '*', 'scope.name', 'promoted', 'scope_name', 'TEXT', 'Instrumentation scope.', NULL, '2026-07-13', NULL),
('events', '*', 'scope.version', 'promoted', 'scope_version', 'TEXT', 'Scope version.', NULL, '2026-07-13', NULL),
('events', '*', 'session.id', 'promoted', 'session_id', 'UUID', 'Claude Code session UUID.', 'session facts', '2026-07-13', NULL),
('events', '*', 'prompt.id', 'promoted', 'prompt_id', 'UUID', 'Prompt UUID.', 'prompt correlation', '2026-07-13', NULL),
('events', '*', 'user.email', 'promoted', 'user_email', 'TEXT', 'Developer identity (normalized).', 'dim_user join', '2026-07-13', 'identity kept per #6'),
('events', '*', 'user.account_uuid', 'promoted', 'user_account_id', 'TEXT', 'Anthropic account UUID.', NULL, '2026-07-13', NULL),
('events', '*', 'user.account_id', 'promoted', 'user_account_id', 'TEXT', 'Anthropic tagged account id.', NULL, '2026-07-13', 'coalesced into user_account_id under user.account_uuid'),
('events', '*', 'organization.id', 'promoted', 'organization_id', 'TEXT', 'Organization UUID.', NULL, '2026-07-13', NULL),
('events', '*', 'app.version', 'promoted', 'cc_version', 'TEXT', 'Claude Code version.', 'install health', '2026-07-13', 'coalesced over resource service.version'),
('events', '*', 'event.sequence', 'promoted', 'event_sequence', 'BIGINT', 'Per-session event ordinal.', NULL, '2026-07-13', NULL),
('events', '*', 'model', 'promoted', 'model', 'TEXT', 'Model id (api_request/assistant_response).', 'fact_api_usage', '2026-07-13', NULL),
('events', '*', 'request_id', 'promoted', 'request_id', 'TEXT', 'Anthropic API request id.', NULL, '2026-07-13', NULL),
('events', '*', 'speed', 'promoted', 'speed', 'TEXT', 'fast/normal.', NULL, '2026-07-13', NULL),
('events', '*', 'effort', 'promoted', 'effort', 'TEXT', 'Reasoning-effort level.', 'fact_api_usage', '2026-07-13', NULL),
('events', '*', 'query_source', 'promoted', 'query_source', 'TEXT', 'Request origin.', 'fact_api_usage', '2026-07-13', NULL),
('events', '*', 'skill.name', 'promoted', 'skill_name', 'TEXT', 'Skill name (skill_activated/api_request).', 'bridge_session_skill', '2026-07-13', NULL),
('events', '*', 'agent.name', 'promoted', 'agent_name', 'TEXT', 'Agent attribution (api_request).', 'bridge_session_agent', '2026-07-13', 'schema-v2 add'),
('events', '*', 'plugin.name', 'promoted', 'plugin_name', 'TEXT', 'Plugin name (plugin_loaded).', 'bridge_session_plugin', '2026-07-13', 'schema-v2 add'),
('events', '*', 'marketplace.name', 'promoted', 'marketplace_name', 'TEXT', 'Marketplace attribution.', NULL, '2026-07-13', 'schema-v2 add'),
('events', '*', 'mcp_server.name', 'promoted', 'mcp_server_name', 'TEXT', 'MCP server attribution (api_request).', 'bridge_session_mcp', '2026-07-13', 'schema-v2 add'),
('events', '*', 'mcp_tool.name', 'promoted', 'mcp_tool_name', 'TEXT', 'MCP tool attribution (api_request).', NULL, '2026-07-13', 'schema-v2 add'),
('events', '*', 'tool_name', 'promoted', 'tool_name', 'TEXT', 'Tool name (tool_decision/tool_result; incl. mcp__*).', 'bridge_session_mcp', '2026-07-13', NULL),
('events', '*', 'tool_use_id', 'promoted', 'tool_use_id', 'TEXT', 'Tool invocation id.', NULL, '2026-07-13', NULL),
('events', '*', 'decision', 'promoted', 'decision', 'TEXT', 'accept / reject (tool_decision).', NULL, '2026-07-13', NULL),
('events', '*', 'source', 'promoted', 'source', 'TEXT', 'Decision source (tool_decision).', NULL, '2026-07-13', NULL),
('events', '*', 'success', 'promoted', 'success_bool', 'BOOLEAN', 'Success flag where reported.', NULL, '2026-07-13', NULL),
('events', '*', 'hook_name', 'promoted', 'hook_name', 'TEXT', 'Hook name (hook_execution_*/hook_registered).', 'bridge_session_hook', '2026-07-13', NULL),
('events', '*', 'hook_event', 'promoted', 'hook_event', 'TEXT', 'Hook trigger event.', NULL, '2026-07-13', NULL),
('events', 'api_request', 'input_tokens', 'promoted', 'input_tokens', 'BIGINT', 'Prompt tokens.', 'fact_api_usage', '2026-07-13', NULL),
('events', 'api_request', 'output_tokens', 'promoted', 'output_tokens', 'BIGINT', 'Completion tokens.', 'fact_api_usage', '2026-07-13', NULL),
('events', 'api_request', 'cache_creation_tokens', 'promoted', 'cache_creation_tokens', 'BIGINT', 'Cache-write tokens.', 'fact_api_usage', '2026-07-13', NULL),
('events', 'api_request', 'cache_read_tokens', 'promoted', 'cache_read_tokens', 'BIGINT', 'Cache-read tokens.', 'fact_api_usage', '2026-07-13', NULL),
('events', 'api_request', 'cost_usd', 'promoted', 'cost_usd', 'DOUBLE PRECISION', 'Estimated cost.', NULL, '2026-07-13', 'archived; marts are adoption-only (no cost)'),
('events', 'api_request', 'duration_ms', 'promoted', 'duration_ms', 'BIGINT', 'API request duration.', NULL, '2026-07-13', NULL),
('events', 'api_error', 'duration_ms', 'promoted', 'duration_ms', 'BIGINT', 'Failed request duration.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'duration_ms', 'promoted', 'duration_ms', 'BIGINT', 'Tool execution duration.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'duration_ms', 'promoted', 'duration_ms', 'BIGINT', 'Subagent duration.', NULL, '2026-07-13', NULL),
('events', 'user_prompt', 'prompt_length', 'promoted', 'prompt_length', 'BIGINT', 'Prompt length in chars.', 'non-empty session', '2026-07-13', NULL),
('events', 'user_prompt', 'command_name', 'promoted', 'command_name', 'TEXT', 'Slash-command name.', NULL, '2026-07-13', NULL),
('events', 'user_prompt', 'command_source', 'promoted', 'command_source', 'TEXT', 'builtin/custom/mcp.', NULL, '2026-07-13', NULL),
('events', 'permission_mode_changed', 'from_mode', 'promoted', 'from_mode', 'TEXT', 'Permission mode before change.', NULL, '2026-07-13', NULL),
('events', 'permission_mode_changed', 'to_mode', 'promoted', 'to_mode', 'TEXT', 'Permission mode after change.', NULL, '2026-07-13', NULL),
('events', 'permission_mode_changed', 'trigger', 'promoted', 'trigger', 'TEXT', 'Mode-change trigger.', NULL, '2026-07-13', NULL),
('events', 'at_mention', 'mention_type', 'promoted', 'mention_type', 'TEXT', '@-mention target type.', NULL, '2026-07-13', NULL);

-- ===== events: kept (blob-only) =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('events', '*', 'user.id', 'kept', NULL, NULL, 'Anonymous install id.', NULL, '2026-07-13', NULL),
('events', '*', 'terminal.type', 'kept', NULL, NULL, 'Terminal app type.', NULL, '2026-07-13', NULL),
('events', '*', 'event.timestamp', 'kept', NULL, NULL, 'ISO event timestamp.', NULL, '2026-07-13', 'we use timeUnixNano for event_time'),
('events', '*', 'client_request_id', 'kept', NULL, NULL, 'Client request id.', NULL, '2026-07-13', NULL),
('events', '*', 'attempt', 'kept', NULL, NULL, 'API attempt number.', NULL, '2026-07-13', NULL),
('events', '*', 'status_code', 'kept', NULL, NULL, 'HTTP status code.', NULL, '2026-07-13', NULL),
('events', '*', 'stop_reason', 'kept', NULL, NULL, 'Model stop reason.', NULL, '2026-07-13', NULL),
('events', '*', 'workspace.host_paths', 'kept', NULL, NULL, 'Desktop workspace dirs.', NULL, '2026-07-13', NULL),
('events', '*', 'cost_usd_micros', 'kept', NULL, NULL, 'Cost in micros.', NULL, '2026-07-13', 'we use cost_usd'),
('events', '*', 'safe_mode', 'kept', NULL, NULL, 'Safe-mode flag.', NULL, '2026-07-13', NULL),
('events', '*', 'hook_source', 'kept', NULL, NULL, 'Hook source.', NULL, '2026-07-13', NULL),
('events', '*', 'managed_only', 'kept', NULL, NULL, 'Managed-only flag.', NULL, '2026-07-13', NULL),
('events', '*', 'num_hooks', 'kept', NULL, NULL, 'Hook count for the event.', NULL, '2026-07-13', NULL),
('events', '*', 'plugin_id_hash', 'kept', NULL, NULL, 'Plugin id hash.', NULL, '2026-07-13', NULL),
('events', 'assistant_response', 'response_length', 'kept', NULL, NULL, 'Response length in chars.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'num_success', 'kept', NULL, NULL, 'Successful hooks.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'num_blocking', 'kept', NULL, NULL, 'Blocking hooks.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'num_non_blocking_error', 'kept', NULL, NULL, 'Non-blocking hook errors.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'num_cancelled', 'kept', NULL, NULL, 'Cancelled hooks.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'total_duration_ms', 'kept', NULL, NULL, 'Total hook duration.', NULL, '2026-07-13', NULL),
('events', 'hook_registered', 'hook_matcher', 'kept', NULL, NULL, 'Hook matcher pattern.', NULL, '2026-07-13', 'details-gated'),
('events', 'hook_registered', 'hook_type', 'kept', NULL, NULL, 'Hook type.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'plugin.version', 'kept', NULL, NULL, 'Plugin version.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'plugin.scope', 'kept', NULL, NULL, 'Plugin scope.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'enabled_via', 'kept', NULL, NULL, 'Plugin enablement source.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'has_hooks', 'kept', NULL, NULL, 'Plugin declares hooks.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'has_mcp', 'kept', NULL, NULL, 'Plugin declares MCP.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'host_owned_mcp', 'kept', NULL, NULL, 'Host-owned MCP flag.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'skill_path_count', 'kept', NULL, NULL, 'Skill path count.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'command_path_count', 'kept', NULL, NULL, 'Command path count.', NULL, '2026-07-13', NULL),
('events', 'plugin_loaded', 'agent_path_count', 'kept', NULL, NULL, 'Agent path count.', NULL, '2026-07-13', NULL),
('events', 'plugin_installed', 'install.trigger', 'kept', NULL, NULL, 'Install trigger (cli/ui).', NULL, '2026-07-13', NULL),
('events', 'plugin_installed', 'marketplace.is_official', 'kept', NULL, NULL, 'Official-marketplace flag.', NULL, '2026-07-13', NULL),
('events', 'skill_activated', 'skill.source', 'kept', NULL, NULL, 'Skill source.', NULL, '2026-07-13', NULL),
('events', 'skill_activated', 'invocation_trigger', 'kept', NULL, NULL, 'Skill invocation trigger.', NULL, '2026-07-13', NULL),
('events', 'skill_activated', 'skill.kind', 'kept', NULL, NULL, 'Skill kind (workflow).', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'is_async', 'kept', NULL, NULL, 'Async subagent flag.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'total_tokens', 'kept', NULL, NULL, 'Subagent total tokens.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'total_tool_uses', 'kept', NULL, NULL, 'Subagent tool-use count.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'agent_type', 'kept', NULL, NULL, 'Subagent type.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'agent.source', 'kept', NULL, NULL, 'Subagent source.', NULL, '2026-07-13', NULL),
('events', 'subagent_completed', 'is_built_in', 'kept', NULL, NULL, 'Built-in subagent flag.', NULL, '2026-07-13', NULL),
('events', 'feedback_survey', 'event_type', 'kept', NULL, NULL, 'Survey event type.', NULL, '2026-07-13', NULL),
('events', 'feedback_survey', 'appearance_id', 'kept', NULL, NULL, 'Survey appearance id.', NULL, '2026-07-13', NULL),
('events', 'feedback_survey', 'survey_type', 'kept', NULL, NULL, 'Survey type.', NULL, '2026-07-13', NULL),
('events', 'feedback_survey', 'enabled_via_override', 'kept', NULL, NULL, 'Survey override flag.', NULL, '2026-07-13', NULL),
('events', 'internal_error', 'error_name', 'kept', NULL, NULL, 'Error class name (no message).', NULL, '2026-07-13', NULL),
('events', 'internal_error', 'error_code', 'kept', NULL, NULL, 'errno (e.g. ENOENT).', NULL, '2026-07-13', NULL),
('events', 'api_retries_exhausted', 'total_attempts', 'kept', NULL, NULL, 'Total attempts.', NULL, '2026-07-13', NULL),
('events', 'api_retries_exhausted', 'total_retry_duration_ms', 'kept', NULL, NULL, 'Total retry duration.', NULL, '2026-07-13', NULL),
('events', 'api_refusal', 'category', 'kept', NULL, NULL, 'Refusal category enum.', NULL, '2026-07-13', 'enum kept per #8'),
('events', 'api_refusal', 'has_category', 'kept', NULL, NULL, 'Refusal has-category flag.', NULL, '2026-07-13', NULL),
('events', 'api_refusal', 'has_explanation', 'kept', NULL, NULL, 'Refusal has-explanation flag.', NULL, '2026-07-13', NULL),
('events', 'api_refusal', 'server_fallback_hop', 'kept', NULL, NULL, 'Server fallback hop.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'status', 'kept', NULL, NULL, 'Connection status.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'transport_type', 'kept', NULL, NULL, 'Transport type.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'server_scope', 'kept', NULL, NULL, 'Server scope.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'error_code', 'kept', NULL, NULL, 'Connection error code.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'is_plugin', 'kept', NULL, NULL, 'Plugin-provided MCP flag.', NULL, '2026-07-13', NULL),
('events', 'mcp_server_connection', 'server_name', 'kept', NULL, NULL, 'MCP server name (details).', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'tool_input_size_bytes', 'kept', NULL, NULL, 'Tool input size.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'tool_result_size_bytes', 'kept', NULL, NULL, 'Tool result size.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'error_type', 'kept', NULL, NULL, 'Error category (not the message).', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'decision_type', 'kept', NULL, NULL, 'Decision type.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'decision_source', 'kept', NULL, NULL, 'Decision source.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'mcp_server_scope', 'kept', NULL, NULL, 'MCP server scope.', NULL, '2026-07-13', NULL),
('events', 'tool_result', 'tool_input', 'kept', NULL, NULL, 'Tool args JSON (details-gated).', NULL, '2026-07-13', 'not in #8 denylist; revisit if PII review flags'),
('events', 'auth', 'action', 'kept', NULL, NULL, 'login/logout.', NULL, '2026-07-13', NULL),
('events', 'auth', 'auth_method', 'kept', NULL, NULL, 'Auth method.', NULL, '2026-07-13', NULL),
('events', 'auth', 'error_category', 'kept', NULL, NULL, 'Auth error category (no message).', NULL, '2026-07-13', NULL),
('events', 'compaction', 'trigger', 'kept', NULL, NULL, 'Compaction trigger (auto/manual).', NULL, '2026-07-13', NULL),
('events', 'compaction', 'pre_tokens', 'kept', NULL, NULL, 'Pre-compaction tokens.', NULL, '2026-07-13', NULL),
('events', 'compaction', 'post_tokens', 'kept', NULL, NULL, 'Post-compaction tokens.', NULL, '2026-07-13', NULL),
('events', 'compaction', 'precompute_reuse', 'kept', NULL, NULL, 'Precompute-reuse outcome.', NULL, '2026-07-13', NULL),
('events', 'hook_plugin_metrics', 'plugin_id', 'kept', NULL, NULL, 'Plugin id (name@marketplace).', NULL, '2026-07-13', NULL);

-- ===== gateway / version-added standard + body-metadata keys (blob-only) =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('metrics', '*', 'user.groups', 'kept', NULL, NULL, 'IdP group membership (gateway sessions).', NULL, '2026-07-13', 'gateway-oidc identity'),
('metrics', '*', 'identity.source', 'kept', NULL, NULL, 'Identity source (e.g. gateway-oidc).', NULL, '2026-07-13', 'gateway sessions'),
('events', '*', 'user.groups', 'kept', NULL, NULL, 'IdP group membership (gateway sessions).', NULL, '2026-07-13', 'gateway-oidc identity'),
('events', '*', 'identity.source', 'kept', NULL, NULL, 'Identity source (e.g. gateway-oidc).', NULL, '2026-07-13', 'gateway sessions'),
('events', '*', 'workflow.run_id', 'kept', NULL, NULL, 'Workflow run id (wf_...) on workflow-spawned agents.', NULL, '2026-07-13', 'v2.1.202+'),
('events', '*', 'workflow.name', 'kept', NULL, NULL, 'Workflow name (custom unless details).', NULL, '2026-07-13', 'v2.1.202+'),
('events', 'api_request_body', 'body_length', 'kept', NULL, NULL, 'Raw API request body length.', NULL, '2026-07-13', NULL),
('events', 'api_request_body', 'body_truncated', 'kept', NULL, NULL, 'Raw API request body truncated flag.', NULL, '2026-07-13', NULL),
('events', 'api_response_body', 'body_length', 'kept', NULL, NULL, 'Raw API response body length.', NULL, '2026-07-13', NULL),
('events', 'api_response_body', 'body_truncated', 'kept', NULL, NULL, 'Raw API response body truncated flag.', NULL, '2026-07-13', NULL),
('events', 'hook_execution_start', 'hook_definitions', 'kept', NULL, NULL, 'Hook definitions (detailed-beta/details gated).', NULL, '2026-07-13', NULL),
('events', 'hook_execution_complete', 'hook_definitions', 'kept', NULL, NULL, 'Hook definitions (detailed-beta/details gated).', NULL, '2026-07-13', NULL);

-- ===== events: denied (#8 redaction denylist) =====
INSERT INTO meta.column_registry (signal, signal_name, attr_path, status, column_name, data_type, description, useful_for, decided_at, notes) VALUES
('events', '*', 'full_command', 'denied', NULL, NULL, 'Full command line.', NULL, '2026-07-13', '#8 denylist (POC four); sink strips wherever seen'),
('events', '*', 'bash_command', 'denied', NULL, NULL, 'Bash command.', NULL, '2026-07-13', '#8 denylist (POC four)'),
('events', '*', 'file_path', 'denied', NULL, NULL, 'File path.', NULL, '2026-07-13', '#8 denylist (POC four)'),
('events', '*', 'error', 'denied', NULL, NULL, 'Error message.', NULL, '2026-07-13', '#8 denylist (POC four); error_name/error_code/error_type kept'),
('events', '*', 'tool_parameters.full_command', 'denied', NULL, NULL, 'Full command inside tool_parameters.', NULL, '2026-07-13', '#8 recursive tool_parameters sweep (tool_result + tool_decision)'),
('events', '*', 'tool_parameters.bash_command', 'denied', NULL, NULL, 'Bash command inside tool_parameters.', NULL, '2026-07-13', '#8 recursive tool_parameters sweep'),
('events', '*', 'tool_parameters.file_path', 'denied', NULL, NULL, 'File path inside tool_parameters.', NULL, '2026-07-13', '#8 recursive tool_parameters sweep'),
('events', 'user_prompt', 'prompt', 'denied', NULL, NULL, 'Prompt text.', NULL, '2026-07-13', '#8 defense-in-depth (client gate OTEL_LOG_USER_PROMPTS=0)'),
('events', 'assistant_response', 'response', 'denied', NULL, NULL, 'Assistant response text.', NULL, '2026-07-13', '#8 defense-in-depth (client gate OTEL_LOG_ASSISTANT_RESPONSES=0)'),
('events', 'feedback_survey', 'response', 'denied', NULL, NULL, 'Survey free-text response.', NULL, '2026-07-13', '#8 defense-in-depth'),
('events', 'api_request_body', 'body', 'denied', NULL, NULL, 'Raw API request body.', NULL, '2026-07-13', '#8 defense-in-depth (client gate OTEL_LOG_RAW_API_BODIES=0)'),
('events', 'api_request_body', 'body_ref', 'denied', NULL, NULL, 'Raw API request body file ref.', NULL, '2026-07-13', '#8 defense-in-depth'),
('events', 'api_response_body', 'body', 'denied', NULL, NULL, 'Raw API response body.', NULL, '2026-07-13', '#8 defense-in-depth'),
('events', 'api_response_body', 'body_ref', 'denied', NULL, NULL, 'Raw API response body file ref.', NULL, '2026-07-13', '#8 defense-in-depth');

-- noqa: enable=LT05

-- migrate:down

DELETE FROM meta.column_registry;
