/// IS seat roster (#116) — latest dated drop under powerbi/data/seat_roster/ (seat_roster_YYYY-MM-DD.csv).
/// Type 1 latest snapshot (#117): seat_tier = current assignment; dated drops retained on disk so SCD2 stays possible.
table seat_roster
	lineageTag: eeca33a6-72f3-42d2-8c5a-9c229307eff5

	column user_email
		dataType: string
		lineageTag: 3c0a5b71-3c80-4076-8815-bc6094415edc
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = Automatic

	column seat_tier
		dataType: string
		lineageTag: 7e984a18-f4e0-44d8-8c5a-d8066ce48b95
		summarizeBy: none
		sourceColumn: seat_tier

		annotation SummarizationSetBy = Automatic

	partition seat_roster = m
		mode: import
		source =
				let
				  Drops = Table.SelectRows(Folder.Files("D:\projects\cc-otel\powerbi\data\seat_roster"), each Text.StartsWith([Name], "seat_roster_") and Text.EndsWith([Name], ".csv")),
				  Latest = if Table.IsEmpty(Drops) then error "No seat_roster_YYYY-MM-DD.csv drop found in powerbi/data/seat_roster - see the README there" else Table.Sort(Drops, {{"Name", Order.Descending}}){0},
				  Raw = Csv.Document(Latest[Content], [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"user_email", type text}, {"seat_tier", type text}})
				in
				  Typed

	annotation PBI_ResultType = Table

